PROGRAM_FOLDER="/home/pi/raspiKeys/game/"
USER_WAV_FOLDER="/home/pi/raspiKeys/res/backtracks/user_wav/"
USER_MP3_FOLDER="/home/pi/raspiKeys/res/backtracks/user_mp3/"
PROCESSED_WAV_FOLDER="/home/pi/raspiKeys/res/backtracks/processed_wav/"
METRO_TICK_FILE="/home/pi/raspiKeys/res/metro/tick.wav"
MIDI_FOLDER="/home/pi/raspiKeys/res/midi/"
CONFIG_FILE="/home/pi/raspiKeys/config.ini"

COL_BG="black"
COL_MAIN="red"
COL_SEC="green"
COL_TOOLBG="bisque2"
COL_GREY="grey"
