class Colors:
    BTN_STANDARD_BACKGROUND= "#fead84"
    BTN_FOOTER_BACKGROUND= "#ab3481"
    BTN_SIDEBAR_PUSHED = "orange"
    BTN_SIDEBAR_NEUTRAL = "brown"
    NAVBAR_BACKGROUND = "#1F1d36"
    BACKGROUND = "black"
    PRIMARY = "#333333"
    TEXT = "white"
    ERROR = "red"
    SUCCESS = "green"
    WARNING = "orange"
    SLIDER_BACKGROUND = "#222222"
