class Colors:
    WHITE = 'white'
    BTN_FOOTER_BACKGROUND = "#ab3481"
    NAVBAR_BACKGROUND = "#eeeeee"
    BACKGROUND = "#030303"
    DARK = "#333333"
    PRIMARY = '#845ec2'
    TEXT_WHITE = "white"
    TEXT_BLACK = "black"
    ERROR = "#dc3545"
    SUCCESS = "green"
    WARNING = "orange"
    SLIDER_BACKGROUND = "#222222"

    LIGHT_COLOR = '#deeaef'
    SELECTED_COLOR = '#3c859e'

    BTN_BORDER_COLOR = "#eeeeee"
    BTN_BORDER_THICKNESS = 2

    POPUP_BACKGROUND = "#222222"
    CUSTOM_PROGRESSBAR_COLOR = PRIMARY

    BTN_STANDARD_BACKGROUND = BACKGROUND
    BTN_SIDEBAR_NEUTRAL = NAVBAR_BACKGROUND
    BTN_SIDEBAR_PUSHED = BACKGROUND

    CUSTOM_SLIDER_BACKGROUND_COLOR = SELECTED_COLOR
    CUSTOM_SLIDER_TROUGHCOLOR = LIGHT_COLOR
    CUSTOM_SLIDER_ACTIVE_COLOR = PRIMARY

    WAVEFORM_FOREGROUND_COLOR = PRIMARY
    WAVEFORM_BACKGROUND_COLOR = DARK

    KEYBOARD_CANVAS_NOTE_LIGHT = PRIMARY

    TREEVIEW_BACKGROUND_ODD = "#e8e8e8"
    TREEVIEW_BACKGROUND_EVEN= "#dfdfdf"
