class Colors:
    WHITE = 'white'
    BTN_FOOTER_BACKGROUND = "#ab3481"
    NAVBAR_BACKGROUND = "#eeeeee"
    BACKGROUND = "#030303"
    DARK = "#333333"
    PRIMARY = "orange"
    TEXT_WHITE = "white"
    TEXT_BLACK = "black"
    ERROR = "#dc3545"
    SUCCESS = "green"
    WARNING = "orange"
    SLIDER_BACKGROUND = "#222222"

    BTN_BORDER_COLOR = "#eeeeee"
    BTN_BORDER_THICKNESS = 2

    BTN_STANDARD_BACKGROUND = BACKGROUND
    BTN_SIDEBAR_NEUTRAL = NAVBAR_BACKGROUND
    BTN_SIDEBAR_PUSHED = BACKGROUND
